# Generated by Django 5.2 on 2025-05-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Anonim', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pekerjaan', models.CharField(default='Mahasiswa', max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('peserta', 'Peserta'), ('pengajar', 'Pengajar'), ('admin', 'Admin')], default='peserta', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('foto', models.CharField(max_length=255)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kategori')),
                ('pengajar', models.ForeignKey(limit_choices_to={'role': 'pengajar'}, on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
        migrations.CreateModel(
            name='MateriKursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('tipe_materi', models.CharField(choices=[('video', 'Video'), ('modul', 'Modul')], max_length=10)),
                ('file_url', models.CharField(max_length=255)),
                ('urutan', models.IntegerField()),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kursus')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kursus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_sertifikat', models.CharField(max_length=100)),
                ('tanggal_diterbitkan', models.DateField()),
                ('file_url', models.CharField(max_length=255)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kursus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.CharField(max_length=10)),
                ('bukti', models.CharField(max_length=255)),
                ('subscription_start_date', models.DateField()),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kursus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
        migrations.CreateModel(
            name='PendapatanPengajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal', models.DateField()),
                ('pengajar', models.ForeignKey(limit_choices_to={'role': 'pengajar'}, on_delete=django.db.models.deletion.CASCADE, to='main.member')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transaksi')),
            ],
        ),
        migrations.CreateModel(
            name='PendapatanAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal', models.DateField()),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transaksi')),
            ],
        ),
        migrations.CreateModel(
            name='TugasAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=255)),
                ('catatan_pengajar', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('belum dikumpulkan', 'Belum Dikumpulkan'), ('diperiksa', 'Diperiksa'), ('lulus', 'Lulus'), ('tidak lulus', 'Tidak Lulus')], default='belum dikumpulkan', max_length=20)),
                ('tanggal_dikumpulkan', models.DateField(blank=True, null=True)),
                ('tanggal_dinilai', models.DateField(blank=True, null=True)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kursus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
    ]
