# Generated by Django 5.2 on 2025-07-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='bukti',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_transaksi/'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='subscription_start_date',
            field=models.DateField(editable=False),
        ),
    ]
