# Generated by Django 5.2 on 2025-06-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materikursus',
            name='file_url',
            field=models.FileField(upload_to='materi_files/'),
        ),
        migrations.AlterModelTable(
            name='member',
            table='main_member',
        ),
    ]
