# Generated by Django 5.2 on 2025-07-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_transaksi_bukti_alter_transaksi_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='subscription_start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
