# Generated by Django 5.2 on 2025-05-22 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_kategori_remove_member_name_remove_member_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursus',
            name='pengajar',
            field=models.ForeignKey(limit_choices_to={'role': 'pengajar'}, on_delete=django.db.models.deletion.CASCADE, to='main.member'),
        ),
        migrations.AlterField(
            model_name='pendapatanpengajar',
            name='pengajar',
            field=models.ForeignKey(limit_choices_to={'role': 'pengajar'}, on_delete=django.db.models.deletion.CASCADE, to='main.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('peserta', 'Peserta'), ('pengajar', 'Pengajar'), ('admin', 'Admin')], default='peserta', max_length=10),
        ),
        migrations.DeleteModel(
            name='Pengajar',
        ),
    ]
