# Generated by Django 5.2 on 2025-06-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_materikursus_file_url_alter_member_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='total_harga',
        ),
        migrations.AddField(
            model_name='kursus',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
